import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RecoilRootWrapper from "@/recoil/recoil_wrapper";

const pretendard = localFont({
  src: "./fonts/Pretendard.woff2",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Boilerplate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <RecoilRootWrapper>
        <body className={pretendard.variable}>{children}</body>
      </RecoilRootWrapper>
    </html>
  );
}
